# Generated by Django 4.2.7 on 2023-12-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activitymanager", "0002_exercise_exercise_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                ("exercise_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=255)),
                ("exercise_distance", models.IntegerField()),
                ("exercise_description", models.CharField(max_length=1000)),
                ("exercise_date", models.DateField()),
                ("exercise_time", models.IntegerField()),
                ("exercise_intensity", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitymanager.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Other",
            fields=[
                ("exercise_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=255)),
                ("exercise_distance", models.IntegerField()),
                ("exercise_description", models.CharField(max_length=1000)),
                ("exercise_date", models.DateField()),
                ("exercise_time", models.IntegerField()),
                ("exercise_intensity", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitymanager.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("exercise_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=255)),
                ("exercise_type", models.CharField(max_length=50)),
                ("exercise_distance", models.IntegerField()),
                ("exercise_description", models.CharField(max_length=1000)),
                ("exercise_date", models.DateField()),
                ("exercise_time", models.IntegerField()),
                ("exercise_intensity", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitymanager.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Swim",
            fields=[
                ("exercise_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=255)),
                ("exercise_distance", models.IntegerField()),
                ("exercise_description", models.CharField(max_length=1000)),
                ("exercise_date", models.DateField()),
                ("exercise_time", models.IntegerField()),
                ("exercise_intensity", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitymanager.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
    ]
