# Generated by Django 4.2.7 on 2023-12-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activitymanager", "0003_bike_other_run_swim_delete_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("exercise_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exercise_name", models.CharField(max_length=255)),
                ("exercise_type", models.CharField(max_length=50)),
                ("exercise_distance", models.IntegerField()),
                ("exercise_description", models.CharField(max_length=1000)),
                ("exercise_date", models.DateField()),
                ("exercise_time", models.IntegerField()),
                ("exercise_intensity", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activitymanager.user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="other",
            name="user",
        ),
        migrations.RemoveField(
            model_name="run",
            name="user",
        ),
        migrations.RemoveField(
            model_name="swim",
            name="user",
        ),
        migrations.DeleteModel(
            name="Bike",
        ),
        migrations.DeleteModel(
            name="Other",
        ),
        migrations.DeleteModel(
            name="Run",
        ),
        migrations.DeleteModel(
            name="Swim",
        ),
    ]
